name: CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  terraform:
    uses: saidsef/saidsef/.github/workflows/tf-validate.yaml@main
    with:
      start-version: '0' # minimum version (format: 1.0.x)
      end-version: '10' # maximum version (format: 1.10.x)

  opentofu:
    uses: saidsef/saidsef/.github/workflows/tf-validate.yaml@main
    with:
      start-version: '5' # minimum version (format: 1.5.x)
      end-version: '8' # maximum version (format: 1.8.x)

  tfsec:
    uses: saidsef/saidsef/.github/workflows/tf-security.yaml@main
    needs: [terraform, opentofu]

  attest:
    uses: saidsef/saidsef/.github/workflows/tf-attest.yaml@main
    needs: [tfsec]

  auto-approve:
    uses: saidsef/saidsef/.github/workflows/auto-approve.yaml@main
    needs: [terraform, opentofu, tfsec]
